In [1]:
import torch
import numpy as np


In [2]:
a = torch.ones (3)
print (a)

tensor([1., 1., 1.])


In [3]:
a [2] = 17
print (a)

tensor([ 1.,  1., 17.])


In [4]:
## convert to torch.tensor
b =[4.0, 1.0, 5.0, 3.0, 2.0, 1.0]
b_t= torch.tensor(b)
b_t

tensor([4., 1., 5., 3., 2., 1.])

In [5]:
## convert to torch tensor
c=[[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]
c_t = torch.tensor (c)
c_t

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [6]:
## print shape
print (c_t.shape)

torch.Size([3, 2])


In [7]:

d_t = torch.zeros(3,2)
print (d_t)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [8]:
## indexing

d_t [0,1] = 17
print (d_t)

d_t [1,1] = 14
print (d_t)

tensor([[ 0., 17.],
        [ 0.,  0.],
        [ 0.,  0.]])
tensor([[ 0., 17.],
        [ 0., 14.],
        [ 0.,  0.]])


In [9]:
## slicing

d_t [1,:]
print (d_t)

tensor([[ 0., 17.],
        [ 0., 14.],
        [ 0.,  0.]])


In [10]:
## shape

d_t.shape


torch.Size([3, 2])

In [11]:
## unsqueese ... means 3D

d_t_unsqueeze = d_t[..., None]

print (d_t_unsqueeze)

tensor([[[ 0.],
         [17.]],

        [[ 0.],
         [14.]],

        [[ 0.],
         [ 0.]]])


In [12]:
d_t_unsqueeze = d_t[None, ...]
d_t_unsqueeze.shape


torch.Size([1, 3, 2])

In [13]:
## color picture example 

batch_t = torch.rand (2,3,5,5) ## first one is batch, 2nd is channels for RGB, 3rt is 32, rows, columns
print (batch_t)
batch_t.shape

tensor([[[[0.0111, 0.3038, 0.8065, 0.8694, 0.3658],
          [0.0178, 0.8467, 0.5241, 0.6227, 0.8853],
          [0.7299, 0.5714, 0.1390, 0.9347, 0.8943],
          [0.2104, 0.8449, 0.0109, 0.5793, 0.5994],
          [0.9999, 0.7398, 0.2922, 0.7870, 0.5668]],

         [[0.0670, 0.0437, 0.7537, 0.4795, 0.6276],
          [0.2259, 0.8546, 0.6202, 0.7366, 0.5439],
          [0.9084, 0.0670, 0.5273, 0.8952, 0.1003],
          [0.3863, 0.6317, 0.4147, 0.2537, 0.8148],
          [0.7981, 0.0990, 0.3291, 0.2753, 0.5850]],

         [[0.8982, 0.8756, 0.7584, 0.0125, 0.8613],
          [0.6004, 0.7569, 0.3784, 0.0293, 0.7291],
          [0.5773, 0.9656, 0.1224, 0.8993, 0.0283],
          [0.4063, 0.8642, 0.2973, 0.3079, 0.8149],
          [0.2502, 0.5632, 0.2529, 0.4479, 0.9814]]],


        [[[0.5981, 0.5756, 0.1444, 0.3568, 0.5157],
          [0.9926, 0.4062, 0.6297, 0.0580, 0.6058],
          [0.9525, 0.2502, 0.4844, 0.9684, 0.7443],
          [0.3855, 0.0029, 0.2538, 0.0192, 0.4342],
    

torch.Size([2, 3, 5, 5])

In [14]:
## data types (sometimes, ph changed data type on assignment or problems)

double_points = torch.ones (10,2, dtype = torch.double)
double_points
double_points.dtype

torch.float64

In [15]:
## torch to numpy

points = torch.ones(3,4)

In [16]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
points_np = points.numpy ()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [18]:
points_t = torch.from_numpy (points_np)
points_t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])