In [1]:
import torch
import numpy as np

import matplotlib.pyplot as plt


In [2]:
a = np.array ([4,5,2,6,8])
print (a)

[4 5 2 6 8]


In [3]:
a = np.array ([1,3,2,5] , dtype='float32')
print (a)

[1. 3. 2. 5.]


In [4]:
list_of_list = ([1,2,3], [4,4,5], [6,2])
b = np.array(list_of_list)
print (b)

[list([1, 2, 3]) list([4, 4, 5]) list([6, 2])]


/Users/jack/anaconda3/envs/py37_ITS5200_2/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [5]:
b = np.zeros(10, dtype=int)
print (b)

[0 0 0 0 0 0 0 0 0 0]


In [6]:
b = np.ones((2,6), dtype=float)
print (b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [7]:
b = np.full((3,3), 42)
print(b)

[[42 42 42]
 [42 42 42]
 [42 42 42]]


In [8]:
b = np.arange (1,30, 3)
print (b)

[ 1  4  7 10 13 16 19 22 25 28]


In [9]:
b= np.linspace (0,10, 10)
print (b)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [10]:
b = np.random.random((5,3,1))
print (b)

[[[0.93131042]
  [0.43157966]
  [0.18661425]]

 [[0.56100242]
  [0.55781776]
  [0.23151361]]

 [[0.85885083]
  [0.89724605]
  [0.23512842]]

 [[0.39620177]
  [0.5417161 ]
  [0.91624013]]

 [[0.78600859]
  [0.95939347]
  [0.56225705]]]


In [11]:
## mean 0 and standard deviation 1

b = np.random.normal(0,1,(4,2,3))
print (b)

[[[ 0.1800816  -0.07611525 -0.23710778]
  [-0.56748097 -0.94805315 -0.24679842]]

 [[-1.01459189  0.78725041 -1.10000645]
  [ 0.07112567  1.17772079  1.17714697]]

 [[ 0.51273865 -0.48256892  0.21646347]
  [-0.00536334 -0.97328424 -0.26882158]]

 [[ 0.89615999  0.09857591  0.24877866]
  [ 0.69529735 -0.45837259 -0.20026276]]]


In [12]:
## indentity matrix

b= np.eye(4)
print (b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
b1 = np.random.randint(20, size =6)
b2 = np.random.randint(20, size =(3,4))
b3 = np.random.randint(20, size = (3,4,6))
print (b1)
print (b2)
print (b3)

print ("b2 dimension", b2.ndim)
print("b3 shape", b3.shape)
print("data type of b3", b3.dtype)

[13 11  7 19  5 17]
[[17 15  3 14]
 [12 13 19 10]
 [ 9 16  7  9]]
[[[14 11 13 12 17  6]
  [ 6 19  9 10  1  0]
  [12 14 15  3 14  6]
  [ 0  9  9 12  2 18]]

 [[ 2 18  4  0  2 18]
  [ 5  3  7 15 12  7]
  [18 11  6  9 15 17]
  [ 1  6 19 10 15  7]]

 [[15  5 15  9  9 13]
  [14 10  9  1 11  6]
  [ 5 18 18  5 10  3]
  [ 7  7  8 12 19 14]]]
b2 dimension 2
b3 shape (3, 4, 6)
data type of b3 int64


In [14]:
## indexing
a = np.array([1,3,2,5], dtype='float32')
print(a)
print ("first num", a[0])
print("third num", a[2])
print("last num", a[-1])
print ("before last num", a[-2])

[1. 3. 2. 5.]
first num 1.0
third num 2.0
last num 5.0
before last num 2.0


In [15]:
## indexing
a = np.array ([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]
              ])

print (a)
print ("first", a[0,0])
print("last num", a[2,-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
first 1
last num 12


In [16]:
## slicing

x = np.arange(15)
print (x)
print ("first 4 elements", x[:4])
print ("all after 3", x[3:])
print ("even indeces", x[::2]) ##starts at 0   ## 2 is the step size
print ("uneven indeces", x[1::2]) ## starts at 1
print ("reverse", x[::-1]) ## step value is negetive starts at last element

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
first 4 elements [0 1 2 3]
all after 3 [ 3  4  5  6  7  8  9 10 11 12 13 14]
even indeces [ 0  2  4  6  8 10 12 14]
uneven indeces [ 1  3  5  7  9 11 13]
reverse [14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [17]:
## slicing

a = np.array ([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]
              ])
print (a)
print (" ")
print (a[:2,:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
[[1 2]
 [5 6]]


In [18]:
a = np.array ([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]
              ])
print (a)
print ("a[:-1,:-1]")
print (a[:-1,:-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a[:-1,:-1]
[[1 2 3]
 [5 6 7]]


In [19]:
a = np.array ([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]
              ])
print (a)
print ("a[:-1,:-1]")
print (a[:-1,:-2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a[:-1,:-1]
[[1 2]
 [5 6]]


In [20]:
## shifting

x = np.arange (15)
print (x)
print ("shift right", x[:-1])
print ("shift left", x[1:])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shift right [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
shift left [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [35]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]] )
print(a)
print ("column 1")
print (a[ :, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
column 1
[ 2  6 10]


In [22]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]] )
print(a)
print("row 1 ")
print(a[1, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
row 1 
[5 6 7 8]


In [23]:
## slicing is numpy does not copy array but
## instead still modifies the original.
## to copy use .copy()
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]] )

new_a = a [:2, :2]
print (a)
print (new_a)

new_a[0,0] = 89
print (a)

new_a2 = a[:2, :2].copy()
print (a)

new_a2[0,0] = 55
print (a)
print (new_a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[89  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[89  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[89  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[55  2]
 [ 5  6]]


In [24]:
a = np.arange(1,10)
b = a.reshape ((3,3))

print (a)
print (b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
v = np.array(  [1, 2, 3, 4, 5]  )
v1 = np.array(  [5, 5, 5, 5, 5]  )

m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]] )

print ("reshape as row vector with reshape", v.reshape ((1,5)))
print ("reshape as row vector with newaxis", v1[np.newaxis,:])
print ("reshape as column vector with newaxis")
print (v1[:, np.newaxis])
print ("reshape matrix m[:, np.newaxis, np.newaxis, :] with newaxis ")
print ( m[:,np.newaxis, np.newaxis,:])
print (m[np.newaxis,:,:, np.newaxis])

reshape as row vector with reshape [[1 2 3 4 5]]
reshape as row vector with newaxis [[5 5 5 5 5]]
reshape as column vector with newaxis
[[5]
 [5]
 [5]
 [5]
 [5]]
reshape matrix m[:, np.newaxis, np.newaxis, :] with newaxis 
[[[[ 1  2  3  4]]]


 [[[ 5  6  7  8]]]


 [[[ 9 10 11 12]]]]
[[[[ 1]
   [ 2]
   [ 3]
   [ 4]]

  [[ 5]
   [ 6]
   [ 7]
   [ 8]]

  [[ 9]
   [10]
   [11]
   [12]]]]


In [26]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11])
ab = np.concatenate ([a,b])
abc = np.concatenate ([a,b,c])
print(a)
print(b)
print(c)
print("concatenate a with b", ab)
print("concatenate a with b with c", abc)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11]
concatenate a with b [1 2 3 4 5 6 7 8]
concatenate a with b with c [ 1  2  3  4  5  6  7  8  9 10 11]


In [27]:
m1 = np.array([ [1,2,3],
                [4,5,6],
                [7,8,9]  ])
                
m2 = np.array([ [10,11,12],
                [13,14,14],
                [16,17,18]  ])
                
print(m1)
print(m2)
m1_m2_concat = np.concatenate([m1, m2], axis=0)
print("m1 m2 concat axis 0 ")
print(m1_m2_concat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 14]
 [16 17 18]]
m1 m2 concat axis 0 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 14]
 [16 17 18]]


In [28]:
m1 = np.array([ [1,2,3],
                [4,5,6],
                [7,8,9]  ])
                
m2 = np.array([ [10,11,12],
                [13,14,14],
                [16,17,18]  ])
                
print(m1)
print(m2)
m1_m2_concat= np.concatenate([m1,m2], axis = 1)
print ("m1,m2 concatenate axis 1")
print (m1_m2_concat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 14]
 [16 17 18]]
m1,m2 concatenate axis 1
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 14]
 [ 7  8  9 16 17 18]]


In [29]:
## np.vstack -->> vertical stack
## np.hstack -->> horizontal stack

m1 = np.array([ [1,2,3],
                [4,5,6],
                [7,8,9]  ])
                
m2 = np.array([ [10,11,12],
                [13,14,14],
                [16,17,18]  ])
                
print(m1)
print(m2)

m1_m2_concat = np.vstack ([m1,m2])
print ("vstack")
print (m1_m2_concat)

m1_m2_concat2 = np.hstack ([m1,m2])
print ("hstack")
print (m1_m2_concat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 14]
 [16 17 18]]
vstack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 14]
 [16 17 18]]
hstack
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 14]
 [ 7  8  9 16 17 18]]


In [30]:
## math operations in numpy

x = np.array ([1,2,3,4])
print (x)
print ("x +10", x+10)
print ("x -10", x-10)
print ("x *10", x*10)
print ("x /2", x/2)
print ("-x", -x)
print ("x **3", x **3)
print ("4^x", np.power(4,x))
print("  np.log(x) ", np.log(x))
print(" np.log2(x)", np.log2(x))
print("np.log10(x)", np.log10(x) )


[1 2 3 4]
x +10 [11 12 13 14]
x -10 [-9 -8 -7 -6]
x *10 [10 20 30 40]
x /2 [0.5 1.  1.5 2. ]
-x [-1 -2 -3 -4]
x **3 [ 1  8 27 64]
4^x [  4  16  64 256]
  np.log(x)  [0.         0.69314718 1.09861229 1.38629436]
 np.log2(x) [0.        1.        1.5849625 2.       ]
np.log10(x) [0.         0.30103    0.47712125 0.60205999]


In [31]:
                 ## min max n_samples
angles = np.linspace(0,  9,  10)
print (angles)
print ("np.sin")
print (np.sin(angles))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
np.sin
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [32]:
## aggregates and others
## tf.reduce_sum() in tensorflow

x = np.array( [1 , 2, 3, 4, 5]  )
print(x)
print ("np.add.reduce(x)=", np.add.reduce(x))
print ("np.multiply.reduce(x)=", np.multiply.reduce(x))
print ("np.sum(x)=", np.sum(x))
print ("np.min(x)=", np.min(x))
print ("np.max(x)=", np.max(x))

[1 2 3 4 5]
np.add.reduce(x)= 15
np.multiply.reduce(x)= 120
np.sum(x)= 15
np.min(x)= 1
np.max(x)= 5
